(() => {
const S=window.STORE,P=window.PRODUCTS;
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:S.currency}).format(n);
const icon=(name)=>({menu:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M4 7h16M4 12h16M4 17h16"/></svg>',user:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><circle cx="12" cy="8" r="4"/><path d="M4 21c1.4-4.1 4.1-6 8-6s6.6 1.9 8 6"/></svg>',bag:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M6 8h12l1 13H5L6 8Z"/><path d="M9 9V6a3 3 0 0 1 6 0v3"/></svg>'}[name]||'');
function header(){
 const a=S.announcements.map(x=>'<span>'+x+'</span><i>✦</i>').join('');
 $('#site-top').innerHTML='<div class="promo-stack"><div class="marquee"><div class="marquee-track"><div class="marquee-set">'+a+'</div><div class="marquee-set">'+a+'</div></div></div><div class="promo-timer"><span>'+S.promo.label+'</span><strong data-countdown>--d --h --m --s</strong><a href="'+S.promo.href+'">'+S.promo.cta+' →</a></div></div><header class="site-header"><div class="header-left"><button class="header-icon menu-trigger" aria-label="Open menu">'+icon('menu')+'</button></div><a class="brand" href="index.html">'+S.shortName+'<span>'+S.subName+'</span></a><nav class="desktop-nav"><a href="index.html">Home</a><a href="collections.html">Products</a><a href="track-order.html">Track Order</a><a href="contact.html">Contact</a><a href="account.html">Account</a></nav><div class="header-right"><a class="header-icon" href="account.html" aria-label="Account">'+icon('user')+'</a><button class="header-icon cart-trigger" aria-label="Open cart">'+icon('bag')+'<span class="cart-count">0</span></button></div></header><div class="menu-overlay"></div><aside class="menu-drawer"><div class="drawer-top"><span class="drawer-brand">'+S.name+'</span><button class="close-btn menu-close" aria-label="Close menu">×</button></div><nav class="menu-links"><a href="index.html">Home <small>01</small></a><a href="collections.html">Products <small>02</small></a><a href="track-order.html">Track Order <small>03</small></a><a href="contact.html">Contact Us <small>04</small></a><a href="account.html">Account <small>05</small></a><a href="faq.html">FAQ <small>06</small></a></nav><div class="menu-meta"><p>Need help with an order or product information?</p><a href="contact.html">Contact support →</a></div></aside>';
}
function footer(){
 $('#site-bottom').innerHTML='<footer class="footer"><div class="footer-grid"><div class="footer-brand"><a class="footer-logo" href="index.html">'+S.name+'</a><p>Research, thoughtfully considered. A focused catalog, clear information, and a simpler customer experience.</p></div><div><h4>Shop</h4><a href="collections.html">All products</a><a href="collections.html?filter=Featured">Featured</a><a href="collections.html?filter=New%20arrival">New arrivals</a><a href="documentation.html">Documentation</a></div><div><h4>Support</h4><a href="contact.html">Contact us</a><a href="track-order.html">Track order</a><a href="faq.html">FAQ</a><a href="shipping.html">Shipping</a><a href="returns.html">Returns & refunds</a></div><div><h4>Company</h4><a href="about.html">About</a><a href="index.html#standards">Our standards</a><a href="documentation.html">Quality & documentation</a><a href="account.html">Account</a></div><div><h4>Legal</h4><a href="privacy.html">Privacy policy</a><a href="terms.html">Terms of service</a><a href="shipping.html">Shipping policy</a><a href="returns.html">Refund policy</a><a href="disclaimer.html">Disclaimer</a></div></div><div class="footer-bottom"><span>© <span data-year></span> '+S.name+'. All rights reserved.</span><span>Secure checkout · '+S.currency+'</span></div></footer>';
}
function cartShell(){
 document.body.insertAdjacentHTML('beforeend','<div class="cart-overlay"></div><aside class="cart-drawer premium-cart"><div class="cart-head premium-cart-head"><div class="cart-title-row"><h2>Your Cart</h2><span class="cart-item-pill" data-drawer-pill>0 items</span></div><button class="close-btn cart-close" aria-label="Close cart">×</button></div><div class="cart-reserve" data-reserve-wrap hidden><div><span class="reserve-label">CART RESERVED FOR</span><strong data-reserve-time>10:00</strong></div><small>Your cart session is held for 10 minutes at a time.</small></div><div class="cart-shipping premium-shipping" data-shipping-wrap><div class="shipping-copy"><span>COMPLIMENTARY SHIPPING</span><strong data-shipping-msg></strong></div><div class="progress premium-progress"><span data-progress></span></div></div><div class="cart-items premium-items" data-cart-items></div><div class="cart-foot premium-cart-foot"><div class="cart-summary-row"><span>Subtotal</span><strong data-subtotal>$0.00</strong></div><div class="cart-summary-row shipping-row"><span>Shipping</span><span>Calculated at checkout</span></div><a class="checkout-btn premium-checkout" href="checkout.html"><span>Checkout</span><span>→</span></a><a class="view-cart-link" href="cart.html">View Full Cart</a></div></aside>');
}
let cart=JSON.parse(localStorage.getItem('forma-cart-v2')||'[]');
const RESERVE_KEY='forma-cart-reservation-deadline';
let reservationTimer=null;
function reservationMs(){return (S.cartReservationMinutes||10)*60*1000}
function ensureReservation(){
 if(!cart.length){localStorage.removeItem(RESERVE_KEY);return null}
 let deadline=Number(localStorage.getItem(RESERVE_KEY)||0);
 if(!deadline||deadline<=Date.now()){deadline=Date.now()+reservationMs();localStorage.setItem(RESERVE_KEY,String(deadline))}
 return deadline;
}
function reservationRemaining(){
 const deadline=ensureReservation();return deadline?Math.max(0,deadline-Date.now()):0;
}
function formatReservation(ms){
 const total=Math.max(0,Math.ceil(ms/1000)),m=Math.floor(total/60),s=total%60;return String(m).padStart(2,'0')+':'+String(s).padStart(2,'0');
}
function tickReservation(){
 if(!cart.length){$$('[data-reserve-wrap]').forEach(e=>e.hidden=true);return}
 let deadline=Number(localStorage.getItem(RESERVE_KEY)||0);
 if(!deadline||deadline<=Date.now()){deadline=Date.now()+reservationMs();localStorage.setItem(RESERVE_KEY,String(deadline))}
 const text=formatReservation(deadline-Date.now());
 $$('[data-reserve-time]').forEach(e=>e.textContent=text);
 $$('[data-reserve-wrap]').forEach(e=>e.hidden=false);
}
function startReservationTimer(){ensureReservation();tickReservation();if(reservationTimer)clearInterval(reservationTimer);reservationTimer=setInterval(tickReservation,1000)}
function saveCart(){localStorage.setItem('forma-cart-v2',JSON.stringify(cart));ensureReservation();renderCart();renderCheckout&&renderCheckout();renderFullCart();tickReservation()}
function productBySlug(slug){return P.find(p=>p.slug===slug)}
function cartCount(){return cart.reduce((n,l)=>n+l.qty,0)}
function cartSubtotal(){return cart.reduce((n,l)=>{const p=productBySlug(l.slug);return n+(p?p.price*l.qty:0)},0)}
function renderCart(){
 const count=cartCount(), subtotal=cartSubtotal();
 $$('.cart-count').forEach(e=>e.textContent=count);
 const dc=$('[data-drawer-count]');if(dc)dc.textContent='('+count+')';
 const pill=$('[data-drawer-pill]');if(pill)pill.textContent=count+' '+(count===1?'item':'items');
 const sub=$('[data-subtotal]');if(sub)sub.textContent=money(subtotal);
 const progress=$('[data-progress]');if(progress)progress.style.width=Math.min(100,subtotal/S.shippingThreshold*100)+'%';
 const ship=$('[data-shipping-msg]');if(ship)ship.textContent=subtotal>=S.shippingThreshold?'Unlocked':'Add '+money(S.shippingThreshold-subtotal)+' more';
 const shippingWrap=$('[data-shipping-wrap]');if(shippingWrap)shippingWrap.hidden=!count;
 const items=$('[data-cart-items]');
 if(items)items.innerHTML=cart.length?cart.map(l=>{const p=productBySlug(l.slug);if(!p)return'';return '<div class="cart-line premium-line"><img src="'+p.image+'" alt="'+p.name+'"><div class="cart-line-main"><small>'+p.category.toUpperCase()+'</small><h4>'+p.name+'</h4><div class="cart-line-controls"><div class="qty premium-qty"><button data-dec="'+p.slug+'" aria-label="Decrease quantity">−</button><span>'+l.qty+'</span><button data-inc="'+p.slug+'" aria-label="Increase quantity">+</button></div><button class="remove premium-remove" data-remove="'+p.slug+'">Remove</button></div></div><strong class="line-total">'+money(p.price*l.qty)+'</strong></div>'}).join(''):'<div class="empty-cart premium-empty"><div class="empty-icon">◇</div><h3>Your cart is empty.</h3><p>Browse the collection and add a product to begin your cart session.</p><a class="button" href="collections.html">Shop products →</a></div>';
 $$('[data-inc]').forEach(b=>b.onclick=()=>changeQty(b.dataset.inc,1));
 $$('[data-dec]').forEach(b=>b.onclick=()=>changeQty(b.dataset.dec,-1));
 $$('[data-remove]').forEach(b=>b.onclick=()=>removeFromCart(b.dataset.remove));
 tickReservation();
}
function addToCart(slug,qty=1){const line=cart.find(l=>l.slug===slug);if(line)line.qty+=qty;else cart.push({slug,qty});saveCart();openCart()}
function changeQty(slug,d){const l=cart.find(x=>x.slug===slug);if(!l)return;l.qty+=d;if(l.qty<=0)cart=cart.filter(x=>x.slug!==slug);saveCart()}
function removeFromCart(slug){cart=cart.filter(x=>x.slug!==slug);saveCart()}
function openMenu(){$('.menu-drawer').classList.add('open');$('.menu-overlay').classList.add('show');document.body.classList.add('lock')}
function closeMenu(){$('.menu-drawer').classList.remove('open');$('.menu-overlay').classList.remove('show');document.body.classList.remove('lock')}
function openCart(){$('.cart-drawer').classList.add('open');$('.cart-overlay').classList.add('show');document.body.classList.add('lock')}
function closeCart(){$('.cart-drawer').classList.remove('open');$('.cart-overlay').classList.remove('show');document.body.classList.remove('lock')}
function countdown(){}
function productCard(p){return '<article class="product-card" data-cat="'+p.category.toLowerCase()+'" data-name="'+p.name.toLowerCase()+'">'+(p.badge?'<span class="product-badge">'+p.badge+'</span>':'')+'<a class="product-image" href="product.html?slug='+p.slug+'"><img src="'+p.image+'" alt="'+p.name+'"></a><div class="product-body"><span class="product-meta">'+p.category+'</span><h3><a href="product.html?slug='+p.slug+'">'+p.name+'</a></h3><div class="product-price"><strong>'+money(p.price)+'</strong>'+(p.compareAt?'<s>'+money(p.compareAt)+'</s>':'')+'</div><div class="product-card-actions"><a class="text-link" href="product.html?slug='+p.slug+'">View details</a><button class="quick-add" aria-label="Add '+p.name+' to cart" data-add="'+p.slug+'">＋</button></div></div></article>'}
function bindAdds(root=document){$$('[data-add]',root).forEach(b=>b.onclick=()=>addToCart(b.dataset.add))}
function renderGrid(sel,items=P){const el=$(sel);if(!el)return;el.innerHTML=items.map(productCard).join('');bindAdds(el)}
function renderProduct(){
 const root=$('#product-page');if(!root)return;const slug=new URLSearchParams(location.search).get('slug')||P[0].slug,p=productBySlug(slug)||P[0];
 document.title=p.name+' — '+S.name;
 root.innerHTML='<div class="product-layout"><div><div class="gallery-main"><img id="mainProductImage" src="'+p.gallery[0]+'" alt="'+p.name+'"></div><div class="thumbs">'+p.gallery.map((img,i)=>'<button data-thumb="'+img+'"><img src="'+img+'" alt=""></button>').join('')+'</div></div><div class="product-info"><p class="eyebrow">'+p.category+'</p><h1>'+p.name+'</h1><p class="product-sub">'+p.subtitle+'</p><div class="product-main-price"><strong>'+money(p.price)+'</strong>'+(p.compareAt?'<s>'+money(p.compareAt)+'</s>':'')+'</div><p class="product-sub">'+p.description+'</p><p class="option-label">Select option</p><div class="variant-row">'+p.variants.map((v,i)=>'<button class="variant '+(i===0?'selected':'')+'">'+v+'</button>').join('')+'</div><div class="buy-row"><div class="qty-box"><button id="prodDec">−</button><span id="prodQty">1</span><button id="prodInc">+</button></div><button class="product-add" id="prodAdd">Add to cart</button></div><div class="product-note"><span>◇ Tracked delivery</span><span>✓ Documentation area</span></div><div class="product-accordions"><details open><summary>Product information</summary><p>'+p.description+'</p></details><details><summary>Specifications</summary><div class="spec-table">'+p.specs.map(x=>'<div class="spec-row"><span>'+x[0]+'</span><span>'+x[1]+'</span></div>').join('')+'</div></details><details><summary>Documentation</summary><p>'+p.document+'. Replace this with the final batch or product documentation link.</p></details><details><summary>Shipping & support</summary><p>Shipping options and final availability are shown at checkout. Visit the support page if you need help before ordering.</p></details></div></div></div><section class="section" style="padding-left:0;padding-right:0"><div class="section-head"><div><p class="eyebrow">YOU MAY ALSO LIKE</p><h2 class="section-title">Related products.</h2></div></div><div class="product-grid" id="related-grid"></div></section><div class="sticky-atc premium-sticky-atc" id="stickyAtc"><div class="sticky-reserve" data-reserve-wrap hidden><span>Cart reserved</span><strong data-reserve-time>10:00</strong></div><div class="sticky-product"><img src="'+p.image+'" alt=""><div class="sticky-info"><strong>'+p.name+'</strong><small>'+money(p.price)+'</small></div><div class="sticky-qty"><button id="stickyDec" type="button">−</button><span id="stickyQty">1</span><button id="stickyInc" type="button">+</button></div><button id="stickyAdd" class="sticky-add-btn" type="button">Add to cart</button></div></div>';
 let q=1;const qEl=$('#prodQty'),sq=$('#stickyQty');const syncQ=()=>{qEl.textContent=q;if(sq)sq.textContent=q};$('#prodInc').onclick=()=>{q++;syncQ()};$('#prodDec').onclick=()=>{q=Math.max(1,q-1);syncQ()};if($('#stickyInc'))$('#stickyInc').onclick=()=>{q++;syncQ()};if($('#stickyDec'))$('#stickyDec').onclick=()=>{q=Math.max(1,q-1);syncQ()};$('#prodAdd').onclick=()=>addToCart(p.slug,q);$('#stickyAdd').onclick=()=>addToCart(p.slug,q);$$('.variant').forEach(v=>v.onclick=()=>{$$('.variant').forEach(x=>x.classList.remove('selected'));v.classList.add('selected')});$$('[data-thumb]').forEach(t=>t.onclick=()=>$('#mainProductImage').src=t.dataset.thumb);renderGrid('#related-grid',P.filter(x=>x.slug!==p.slug).slice(0,4));const atc=$('#stickyAtc');window.addEventListener('scroll',()=>atc.classList.toggle('show',window.scrollY>500));
}
function initCatalog(){
 const grid=$('#catalog-grid'),search=$('#catalogSearch');if(!grid)return;let active=(new URLSearchParams(location.search).get('filter')||'all').toLowerCase();const apply=()=>{const q=(search?.value||'').toLowerCase();const items=P.filter(p=>(active==='all'||p.category.toLowerCase()===active)&&(!q||p.name.toLowerCase().includes(q)||p.category.toLowerCase().includes(q)));renderGrid('#catalog-grid',items);const n=$('#catalogCount');if(n)n.textContent=items.length+' products'};renderGrid('#catalog-grid');search&&search.addEventListener('input',apply);$$('[data-filter]').forEach(b=>{b.classList.toggle('active',b.dataset.filter.toLowerCase()===active);b.onclick=()=>{active=b.dataset.filter.toLowerCase();$$('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));apply()}});apply()
}
function initTracking(){
 const form=$('#trackForm'),result=$('#trackResult'),demo=$('#demoTrack');if(!form)return;form.onsubmit=e=>{e.preventDefault();$('#trackStatus').textContent='Live order lookup is not connected yet. Use the demo below to preview the finished experience.'};demo.onclick=()=>{result.hidden=false;result.scrollIntoView({behavior:'smooth',block:'start'})}
}
function initContact(){const f=$('#contactForm');if(f)f.onsubmit=e=>{e.preventDefault();$('#contactStatus').textContent='The support form design is ready. Email delivery will be connected before launch.'}}
function initAccount(){const f=$('#loginForm');if(f)f.onsubmit=e=>{e.preventDefault();$('#loginStatus').textContent='Account authentication will be connected before launch.'}}
function renderCheckout(){
 const root=$('#checkout-summary');if(!root)return;const subtotal=cartSubtotal(),shipping=subtotal>=S.shippingThreshold?0:7.95;root.innerHTML=(cart.length?cart.map(l=>{const p=productBySlug(l.slug);return '<div class="summary-line"><span>'+p.name+' × '+l.qty+'</span><strong>'+money(p.price*l.qty)+'</strong></div>'}).join(''):'<div class="summary-line"><span>Your cart is empty</span><span>—</span></div>')+'<div class="summary-line"><span>Subtotal</span><strong>'+money(subtotal)+'</strong></div><div class="summary-line"><span>Shipping</span><strong>'+(shipping===0?'Free':money(shipping))+'</strong></div><div class="summary-line total"><strong>Estimated total</strong><strong>'+money(subtotal+shipping)+'</strong></div>'
}
function renderFullCart(){
 const root=$('#fullCart');if(!root)return;
 const subtotal=cartSubtotal(),count=cartCount();
 root.innerHTML='<div class="full-cart-layout"><div><div class="full-cart-reserve" data-reserve-wrap '+(count?'':'hidden')+'><div><span>CART RESERVED FOR</span><strong data-reserve-time>'+formatReservation(reservationRemaining())+'</strong></div><small>Your cart session refreshes every 10 minutes while items remain.</small></div><div class="full-cart-items">'+(cart.length?cart.map(l=>{const p=productBySlug(l.slug);return '<article class="full-cart-line"><img src="'+p.image+'" alt="'+p.name+'"><div><small>'+p.category.toUpperCase()+'</small><h3>'+p.name+'</h3><p>'+money(p.price)+' each</p><div class="qty premium-qty"><button data-fdec="'+p.slug+'">−</button><span>'+l.qty+'</span><button data-finc="'+p.slug+'">+</button></div><button class="remove premium-remove" data-fremove="'+p.slug+'">Remove</button></div><strong>'+money(p.price*l.qty)+'</strong></article>'}).join(''):'<div class="empty-cart premium-empty"><h3>Your cart is empty.</h3><p>Add a product to start your 10-minute cart reservation session.</p><a class="button" href="collections.html">Shop products →</a></div>')+'</div></div><aside class="full-cart-summary"><p class="eyebrow">ORDER SUMMARY</p><div class="cart-summary-row"><span>Subtotal</span><strong>'+money(subtotal)+'</strong></div><div class="cart-summary-row shipping-row"><span>Shipping</span><span>Calculated at checkout</span></div><div class="premium-shipping full-cart-shipping" '+(count?'':'hidden')+'><div class="shipping-copy"><span>COMPLIMENTARY SHIPPING</span><strong>'+(subtotal>=S.shippingThreshold?'Unlocked':'Add '+money(S.shippingThreshold-subtotal)+' more')+'</strong></div><div class="progress premium-progress"><span style="width:'+Math.min(100,subtotal/S.shippingThreshold*100)+'%"></span></div></div><a class="checkout-btn premium-checkout" href="checkout.html"><span>Checkout</span><span>→</span></a><a class="view-cart-link" href="collections.html">Continue shopping</a></aside></div>';
 $$('[data-finc]').forEach(b=>b.onclick=()=>changeQty(b.dataset.finc,1));$$('[data-fdec]').forEach(b=>b.onclick=()=>changeQty(b.dataset.fdec,-1));$$('[data-fremove]').forEach(b=>b.onclick=()=>removeFromCart(b.dataset.fremove));tickReservation();
}
function initCheckout(){const f=$('#checkoutForm');if(f)f.onsubmit=e=>{e.preventDefault();$('#checkoutStatus').textContent='Checkout UI is complete. Connect the server-side crypto provider before accepting payments.'};renderCheckout()}
function bindGlobal(){
 $('.menu-trigger').onclick=openMenu;$('.menu-close').onclick=closeMenu;$('.menu-overlay').onclick=closeMenu;$$('.cart-trigger').forEach(b=>b.onclick=openCart);$('.cart-close').onclick=closeCart;$('.cart-overlay').onclick=closeCart;$$('[data-year]').forEach(e=>e.textContent=new Date().getFullYear());renderCart();startReservationTimer()
}
document.addEventListener('DOMContentLoaded',()=>{header();footer();cartShell();bindGlobal();renderGrid('#home-products',P.slice(0,4));initCatalog();renderProduct();initTracking();initContact();initAccount();initCheckout();renderFullCart();bindAdds()});
})();