window.STORE = {
  name: "Forma Research",
  shortName: "FORMA",
  subName: "RESEARCH",
  currency: "USD",
  shippingThreshold: 250,
  cartReservationMinutes: 10,
  sameDayShipping: { enabled: true, cutoff: "2 PM" },
  shippingOrigin: "Florida",
  moneyBackDays: 30,
  promo: {
    enabled: false,
    label: "",
    endsAt: "",
    cta: "",
    href: "collections.html"
  },
  announcements: [
    "FREE SHIPPING ON ORDERS $250+",
    "PRODUCT DOCUMENTATION ON EVERY LISTING",
    "TRACKED DELIVERY",
    "SUPPORT WHEN YOU NEED IT"
  ]
};

window.PRODUCTS = [
  {
    slug: "retatrutide",
    name: "RETATRUTIDE",
    category: "Peptides",
    price: 49.99,
    compareAt: 57.99,
    badge: "SALE",
    image: "public/images/products/product-1.svg",
    gallery: ["public/images/products/product-1.svg","public/images/products/detail.svg"],
    subtitle: "",
    description: "RETATRUTIDE research reference for laboratory and analytical research use. Product-specific documentation can be linked to each listing.",
    specs: [["Product","RETATRUTIDE"],["Category","Research peptide"],["Available sizes","10 mg · 20 mg · 30 mg · 60 mg"],["Fulfillment","Florida, USA"]],
    variants: [
      {label:"10 mg",amount:10,price:49.99,compareAt:57.99},
      {label:"20 mg",amount:20,price:null},
      {label:"30 mg",amount:30,price:null},
      {label:"60 mg",amount:60,price:null}
    ],
    document: "Batch documentation"
  },
  {
    slug: "ghk-cu",
    name: "GHK-CU",
    category: "Peptides",
    price: null,
    compareAt: null,
    badge: "",
    image: "public/images/products/product-2.svg",
    gallery: ["public/images/products/product-2.svg","public/images/products/detail.svg"],
    subtitle: "",
    description: "GHK-CU research reference for laboratory and analytical research use.",
    specs: [["Product","GHK-CU"],["Category","Research peptide"],["Available sizes","50 mg · 100 mg"],["Fulfillment","Florida, USA"]],
    variants: [{label:"50 mg",amount:50,price:null},{label:"100 mg",amount:100,price:null}],
    document: "Batch documentation",
    pricingPending: true
  },
  {
    slug: "wolverine-blend",
    name: "Wolverine Blend",
    category: "Peptides",
    price: null,
    compareAt: null,
    badge: "",
    image: "public/images/products/product-3.svg",
    gallery: ["public/images/products/product-3.svg","public/images/products/detail.svg"],
    subtitle: "",
    description: "Wolverine Blend research reference for laboratory and analytical research use.",
    specs: [["Product","Wolverine Blend"],["Category","Research blend"],["Available sizes","10 mg · 20 mg"],["Fulfillment","Florida, USA"]],
    variants: [{label:"10 mg",amount:10,price:null},{label:"20 mg",amount:20,price:null}],
    document: "Batch documentation",
    pricingPending: true
  },
  {
    slug: "bpc-157",
    name: "BPC-157",
    category: "Peptides",
    price: null,
    compareAt: null,
    badge: "",
    image: "public/images/products/product-4.svg",
    gallery: ["public/images/products/product-4.svg","public/images/products/detail.svg"],
    subtitle: "",
    description: "BPC-157 research reference for laboratory and analytical research use.",
    specs: [["Product","BPC-157"],["Category","Research peptide"],["Available size","10 mg"],["Fulfillment","Florida, USA"]],
    variants: [{label:"10 mg",amount:10,price:null}],
    document: "Batch documentation",
    pricingPending: true
  },
  {
    slug: "tb-500",
    name: "TB-500",
    category: "Peptides",
    price: null,
    compareAt: null,
    badge: "",
    image: "public/images/products/product-5.svg",
    gallery: ["public/images/products/product-5.svg","public/images/products/detail.svg"],
    subtitle: "",
    description: "TB-500 research reference for laboratory and analytical research use.",
    specs: [["Product","TB-500"],["Category","Research peptide"],["Available size","10 mg"],["Fulfillment","Florida, USA"]],
    variants: [{label:"10 mg",amount:10,price:null}],
    document: "Batch documentation",
    pricingPending: true
  },
  {
    slug: "cjc-1295",
    name: "CJC-1295",
    category: "Peptides",
    price: null,
    compareAt: null,
    badge: "",
    image: "public/images/products/product-6.svg",
    gallery: ["public/images/products/product-6.svg","public/images/products/detail.svg"],
    subtitle: "",
    description: "CJC-1295 research reference for laboratory and analytical research use.",
    specs: [["Product","CJC-1295"],["Category","Research peptide"],["Available sizes","5 mg · 10 mg"],["Fulfillment","Florida, USA"]],
    variants: [{label:"5 mg",amount:5,price:null},{label:"10 mg",amount:10,price:null}],
    document: "Batch documentation",
    pricingPending: true
  },
  {
    slug: "ipamorelin",
    name: "IPAMORELIN",
    category: "Peptides",
    price: null,
    compareAt: null,
    badge: "",
    image: "public/images/products/product-1.svg",
    gallery: ["public/images/products/product-1.svg","public/images/products/detail.svg"],
    subtitle: "",
    description: "IPAMORELIN research reference for laboratory and analytical research use.",
    specs: [["Product","IPAMORELIN"],["Category","Research peptide"],["Available sizes","5 mg · 10 mg"],["Fulfillment","Florida, USA"]],
    variants: [{label:"5 mg",amount:5,price:null},{label:"10 mg",amount:10,price:null}],
    document: "Batch documentation",
    pricingPending: true
  },
  {
    slug: "tesamorelin",
    name: "TESAMORELIN",
    category: "Peptides",
    price: null,
    compareAt: null,
    badge: "",
    image: "public/images/products/product-2.svg",
    gallery: ["public/images/products/product-2.svg","public/images/products/detail.svg"],
    subtitle: "",
    description: "TESAMORELIN research reference for laboratory and analytical research use.",
    specs: [["Product","TESAMORELIN"],["Category","Research peptide"],["Available sizes","10 mg · 20 mg"],["Fulfillment","Florida, USA"]],
    variants: [{label:"10 mg",amount:10,price:null},{label:"20 mg",amount:20,price:null}],
    document: "Batch documentation",
    pricingPending: true
  },
  {
    slug: "igf-1-lr3",
    name: "IGF-1 LR3",
    category: "Peptides",
    price: null,
    compareAt: null,
    badge: "",
    image: "public/images/products/product-3.svg",
    gallery: ["public/images/products/product-3.svg","public/images/products/detail.svg"],
    subtitle: "",
    description: "IGF-1 LR3 research reference for laboratory and analytical research use.",
    specs: [["Product","IGF-1 LR3"],["Category","Research peptide"],["Available size","1 mg"],["Fulfillment","Florida, USA"]],
    variants: [{label:"1 mg",amount:1,price:null}],
    document: "Batch documentation",
    pricingPending: true
  },
  {
    slug: "mots-c",
    name: "MOTS-C",
    category: "Peptides",
    price: null,
    compareAt: null,
    badge: "",
    image: "public/images/products/product-4.svg",
    gallery: ["public/images/products/product-4.svg","public/images/products/detail.svg"],
    subtitle: "",
    description: "MOTS-C research reference for laboratory and analytical research use.",
    specs: [["Product","MOTS-C"],["Category","Research peptide"],["Available sizes","20 mg · 40 mg"],["Fulfillment","Florida, USA"]],
    variants: [{label:"20 mg",amount:20,price:null},{label:"40 mg",amount:40,price:null}],
    document: "Batch documentation",
    pricingPending: true
  },
  {
    slug: "nad-plus",
    name: "NAD+",
    category: "Peptides",
    price: null,
    compareAt: null,
    badge: "",
    image: "public/images/products/product-5.svg",
    gallery: ["public/images/products/product-5.svg","public/images/products/detail.svg"],
    subtitle: "",
    description: "NAD+ research reference for laboratory and analytical research use.",
    specs: [["Product","NAD+"],["Category","Research compound"],["Available sizes","500 mg · 1000 mg"],["Fulfillment","Florida, USA"]],
    variants: [{label:"500 mg",amount:500,price:null},{label:"1000 mg",amount:1000,price:null}],
    document: "Batch documentation",
    pricingPending: true
  },
  {
    slug: "mt-1",
    name: "MT-1",
    category: "Peptides",
    price: null,
    compareAt: null,
    badge: "",
    image: "public/images/products/product-6.svg",
    gallery: ["public/images/products/product-6.svg","public/images/products/detail.svg"],
    subtitle: "",
    description: "MT-1 research reference for laboratory and analytical research use.",
    specs: [["Product","MT-1"],["Category","Research peptide"],["Available size","10 mg"],["Fulfillment","Florida, USA"]],
    variants: [{label:"10 mg",amount:10,price:null}],
    document: "Batch documentation",
    pricingPending: true
  }
];